### ISSUE TITLE
[Bug report] "create directory for syslog clients" create unexpected directory

### ISSUE THREAD

**Issue by jqiuyin** [bodsch/ansible-syslog-ng#10]
In my example,l hope classify logs from udp by ip address.
```
syslog_options:
  keep_hostname: false
  create_dirs: true
  perm: "0644"

syslog_sources:
  s_remote:
    - comment: messages generated by syslog-ng
      udp:
      tcp:

syslog_logs:
  remote:
    source: s_remote
    file_name: "remote/${HOST}/message"
    filter:
      filter:
        - not host("localhost")
```
Due to https://github.com/bodsch/ansible-syslog-ng/blob/9846c9c19edccc8b2e4e9b96302e161e154194b9/tasks/configure.yml#L28 ，it will create "/var/log/remote/${HOST}". it's not what i want, syslog-ng will create the directory like "/var/log/remote/10.x.x.x" by itself if the "create_dirs" option is on
